### ISSUE TITLE
Help needed: Error on build

### ISSUE THREAD

**Issue by urameshibr** [gridaco/code#200]
**Describe the bug**
Error when the application will build in local environment.

**To Reproduce**
1. clone the project
2. yarn
3. yarn editor
4. Showing error

**Expected behavior**
Run the application.

**Screenshots**
<img width="839" alt="image" src="https://user-images.githubusercontent.com/5429620/221386761-3997d882-e9fe-41fd-b3bb-897869491bd2.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0 (chip M1)

**Smartphone (please complete the following information):**

**Comment by softmarshmallow** [comment]
Hi. Did you clone with submodules?
If you cloned this project conventionally, you'll have to run 
`git submodule update --init --recursive`

Or, simply clone using Github Desktop, it will resolve submodules automatically, 

Once this step is property done, 

run 

```
yarn
cd editor
yarn dev
```

**Comment by urameshibr** [comment]
> Hi. Did you clone with submodules? If you cloned this project conventionally, you'll have to run `git submodule update --init --recursive`
> 
> Or, simply clone using Github Desktop, it will resolve submodules automatically,
> 
> Once this step is property done,
> 
> run
> 
> ```
> yarn
> cd editor
> yarn dev
> ```

Thank you very much, fixed.
